name: amejiManager
version: 1.1
main: net.jp.minecraft.plugins.amejiManager
author: syokkendesuyo
description: amejiManager
commands:
    help:
        description: Help Command
        usage: /help
    result:
        description: Result Command
        usage: /result
permissions:
    ameji.use:
        description: default perm
        default: op
